#!/bin/sh

HOST=http://streams-test.herokuapp.com

STREAM=$1

if [ $# == 0 ]
then
  echo "Please enter a name for this stream:"
  read STREAM
fi

STREAM=$(echo $STREAM | sed 's/[^A-Za-z]//g')

echo "You can watch this stream at ${HOST}/watch/${STREAM}"

while [ 1 ]
do
  ./wacaw -d 2 -i 1 ${STREAM}
  curl -T ${STREAM}.jpeg ${HOST}/streams/${STREAM}.jpg
done

